### PR TITLE
Update routing, add components.

### PR DESCRIPTION
**Pull request by timothyshambra**

### CODE REVIEW

**Comment by jasonlally** [comment]
@timothyshambra - When I run it locally I get some unhandled errors on the dataset search page. Below was when accessing: http://localhost:3000/topic/datasets?q=&topic=economy-and-demographics 

image

`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    React 9
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 7
8 react-dom.development.js:14388
    React 9
    performConcurrentWorkOnRoot self-hosted:1198
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 6
    webpackJsonpCallback self-hosted:1198
    <anonymous> NextJS
`

`Uncaught Error: Text content does not match server-rendered HTML.
    React 9
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 7
react-dom.development.js:9644
    React 9
    performConcurrentWorkOnRoot self-hosted:1198
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    (Async: EventHandlerNonNull)
    <anonymous> scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 6
    webpackJsonpCallback self-hosted:1198
    <anonymous> NextJS
`

`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    React 9
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 7
8 react-dom.development.js:14388
`

`Uncaught Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    EventHandlerNonNull* scheduler.development.js:571
    <anonymous> scheduler.development.js:633
    NextJS 4
    <anonymous> index.js:6
    NextJS 4
    React 2
    NextJS 4
    <anonymous> React
    NextJS 4
    <anonymous> index.js:10
    NextJS 4
    <anonymous> next-dev.js:2
    NextJS 7
react-dom.development.js:20658
`

**Comment by Greg-Watanabe** [comment]
@jasonlally 
Could you recheck for the errors? I'm not seeing the error now so it may have been fixed at some point.

**Comment by jasonlally** [comment]
@Greg-Watanabe - looks like it's only happening in Firefox. This page: http://localhost:3000/topic/datasets?q=&topic=covid-19 throws the unhandled errors. I tried it in a private browser as well to make sure it wasn't some weird interaction with extensions.

I tried it in Chrome, Edge and Safari and did not get the same errors. It's a little bit of a head scratcher.

**Comment by jasonlally** [comment]
@Greg-Watanabe - one hypothesis I have is that it might have to do with the other warnings we're getting. Maybe cleaning up those will clean up the hydration error messages.

```
Warning: Extra attributes from the server: tabindex
input
form
div
div
cagov-site-navigation
div
div
div
div
MyApp@webpack-internal:///./pages/_app.js:50:21
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23393
Container@webpack-internal:///./node_modules/next/dist/client/index.js:323:24
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:825:20
Root@webpack-internal:///./node_modules/next/dist/client/index.js:949:21 next-dev.js:25:25
```

```
Warning: Invalid value for prop `submit` on <button> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
button
withEmotionCache/<@webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66
SelectUnstyled@webpack-internal:///./node_modules/@mui/base/SelectUnstyled/SelectUnstyled.js:79:7
CustomSelect@webpack-internal:///./components/BasicSelect.js:88:1
BasicSelect@webpack-internal:///./components/BasicSelect.js:104:18
div
form
div
div
article
main
Results@webpack-internal:///./pages/topic/datasets.js:321:64
MyApp@webpack-internal:///./pages/_app.js:50:21
ErrorBoundary@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20746
ReactDevOverlay@webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23393
Container@webpack-internal:///./node_modules/next/dist/client/index.js:323:24
AppContainer@webpack-internal:///./node_modules/next/dist/client/index.js:825:20
Root@webpack-internal:///./node_modules/next/dist/client/index.js:949:21 next-dev.js:25:25
```

**Comment by Greg-Watanabe** [comment]
@jasonlally  I fixed the Firefox error. The filter arrays were being sorted twice. I changed it to sort them once. Don't know why that caused an error in Firefox but that fixed it.

**Comment by jasonlally** [comment]
@Greg-Watanabe - great, yep looking good!!! Thanks for looking into that.

**Pull request merged**
